---
version: "3"

vars:
  PROJECT: claims
  MODULE: github.com/stuttgart-things/claims
  BIN_DIR: ./bin

includes:
  git:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/tasks/refs/heads/main/git/git.yaml
  lint:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/tasks/refs/heads/main/git/linting.yaml
  goLint:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/tasks/refs/heads/main/go/lint.yaml
  goBuild:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/tasks/refs/heads/main/go/build.yaml

tasks:
  do:
    desc: Select a task to run
    cmds:
      - |
        # Extract task names (keep internal colons, remove only trailing colon)
        task_name=$(task -l | awk '/^\*/ {print $2}' | sed 's/:$//' | gum choose)

        # Run the selected task
        [ -n "$task_name" ] && task "$task_name"

  build:
    desc: Build binary using Dagger with ldflags
    vars:
      VERSION:
        sh: git describe --tags --abbrev=0 2>/dev/null || echo "0.0.1"
      OS: '{{.OS | default "linux"}}'
      ARCH: '{{.ARCH | default "amd64"}}'
      OUTPUT_PATH: '{{.OUTPUT_PATH | default "/tmp/go/build/"}}'
    cmds:
      - task: goBuild:build
        vars:
          SRC: .
          GO_VERSION: "1.25.5"
          OS: "{{ .OS }}"
          ARCH: "{{ .ARCH }}"
          PACKAGE_NAME: "{{ .MODULE }}"
          LDFLAGS: "cmd.version={{ .VERSION }}; cmd.buildDate=$(date -u +%Y-%m-%dT%H:%M:%SZ); cmd.commit=$(git rev-parse --short HEAD 2>/dev/null || echo 'none')"
          GO_MAIN_FILE: main.go
          BIN_NAME: "{{ .PROJECT }}"
          OUTPUT_PATH: "{{ .OUTPUT_PATH }}"

  render:
    desc: Run render in non-interactive mode with test params
    vars:
      PARAMS_FILE: '{{.PARAMS_FILE | default "tests/params.yaml"}}'
      OUTPUT_DIR: '{{.OUTPUT_DIR | default "output"}}'
    cmds:
      - go run . render --non-interactive -f {{.PARAMS_FILE}} -o {{.OUTPUT_DIR}}

  render-inline:
    desc: Run render in non-interactive mode with inline template and params
    vars:
      TEMPLATE: '{{.TEMPLATE | default "vspherevm"}}'
      PARAMS: '{{.PARAMS | default "name=test"}}'
      OUTPUT_DIR: '{{.OUTPUT_DIR | default "output"}}'
    cmds:
      - go run . render --non-interactive -t {{.TEMPLATE}} -p {{.PARAMS}} -o {{.OUTPUT_DIR}}

  test-gitops:
    desc: Run GitOps integration tests
    cmds:
      - ./tests/test_gitops.sh

  release-bin:
    desc: Release binary via goreleaser using Dagger
    cmds:
      - task: git:release
      - task: goBuild:release
        vars:
          SRC: .
          CHECK_ONLY:
            sh: |
              gum choose --header "Perform a dry run only?" "true" "false" || echo "false"
          OUTPUT_PATH: /tmp/claims/goreleaser.log
          RELEASER_VERSION: v2.13.3

  run-claim-api:
    desc: Run claim-machinery-api via Dagger
    vars:
      API_MODULE: '{{ .API_MODULE | default "github.com/stuttgart-things/claim-machinery-api/.dagger"}}'
      API_SOURCE_CODE: '{{.API_SOURCE_CODE | default "https://github.com/stuttgart-things/claim-machinery-api#main"}}'
      API_PROFILE_FILE: '{{.API_PROFILE_FILE | default "tests/api-profile.yaml"}}'
      API_HOST_PORT: '{{.API_HOST_PORT | default "8080"}}'
    cmds:
      - >
        dagger call
        -m {{ .API_MODULE }}
        run-api
        --source "{{ .API_SOURCE_CODE }}"
        --profile-file {{ .API_PROFILE_FILE }}
        --host-port {{ .API_HOST_PORT }}
        up --progress plain
