---
version: "3"

vars:
  PROJECT: claims
  MODULE: github.com/stuttgart-things/claims
  BIN_DIR: ./bin

includes:
  git:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/tasks/refs/heads/main/git/git.yaml
  lint:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/tasks/refs/heads/main/git/linting.yaml
  goLint:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/tasks/refs/heads/main/go/lint.yaml
  goBuild:
    taskfile: https://raw.githubusercontent.com/stuttgart-things/tasks/refs/heads/main/go/build.yaml

tasks:
  do:
    desc: Select a task to run
    cmds:
      - |
        # Extract task names (keep internal colons, remove only trailing colon)
        task_name=$(task -l | awk '/^\*/ {print $2}' | sed 's/:$//' | gum choose)

        # Run the selected task
        [ -n "$task_name" ] && task "$task_name"

  build:
    desc: Build binary using Dagger with ldflags
    vars:
      VERSION:
        sh: git describe --tags --abbrev=0 2>/dev/null || echo "0.0.1"
      OS: '{{.OS | default "linux"}}'
      ARCH: '{{.ARCH | default "amd64"}}'
      OUTPUT_PATH: '{{.OUTPUT_PATH | default "/tmp/go/build/"}}'
    cmds:
      - task: goBuild:build
        vars:
          SRC: .
          GO_VERSION: "1.25.5"
          OS: "{{ .OS }}"
          ARCH: "{{ .ARCH }}"
          PACKAGE_NAME: "{{ .MODULE }}"
          LDFLAGS: "cmd.version={{ .VERSION }}; cmd.buildDate=$(date -u +%Y-%m-%dT%H:%M:%SZ); cmd.commit=$(git rev-parse --short HEAD 2>/dev/null || echo 'none')"
          GO_MAIN_FILE: main.go
          BIN_NAME: "{{ .PROJECT }}"
          OUTPUT_PATH: "{{ .OUTPUT_PATH }}"

  release:
    desc: Release binary via goreleaser using Dagger
    cmds:
      - task: goBuild:release
        vars:
          SRC: .
          CHECK_ONLY: "{{ .CHECK_ONLY | default `false` }}"
          OUTPUT_PATH: /tmp/claims/goreleaser.log
          RELEASER_VERSION: v2.13.3
    vars:
      CHECK_ONLY:
        sh: |
          gum choose --header "Perform a dry run only?" "true" "false" || echo "false"
