package cmd

import (
	"fmt"
	"strings"

	"github.com/stuttgart-things/claims/internal/gitops"
)

// executePRCreation creates a pull request after push
func executePRCreation(results []RenderResult, config *RenderConfig, repoPath string) error {
	if config.PRConfig == nil || !config.PRConfig.Create {
		return nil
	}

	// Check gh authentication
	if err := gitops.CheckGHAuth(); err != nil {
		return err
	}

	// Generate title if not provided
	title := config.PRConfig.Title
	if title == "" {
		var names []string
		for _, r := range results {
			if r.Error == nil {
				names = append(names, r.TemplateName)
			}
		}
		title = fmt.Sprintf("Rendered claims: %s", strings.Join(names, ", "))
	}

	// Generate description if not provided
	description := config.PRConfig.Description
	if description == "" {
		description = generatePRDescription(results, config)
	}

	// Determine head branch (current branch or specified branch)
	headBranch := ""
	if config.GitConfig != nil && config.GitConfig.Branch != "" {
		headBranch = config.GitConfig.Branch
	}

	// Determine base branch
	baseBranch := config.PRConfig.BaseBranch
	if baseBranch == "" {
		baseBranch = "main"
	}

	prConfig := gitops.PRConfig{
		Title:       title,
		Description: description,
		Labels:      config.PRConfig.Labels,
		BaseBranch:  baseBranch,
		HeadBranch:  headBranch,
	}

	fmt.Println("Creating pull request...")
	pr, err := gitops.CreatePR(prConfig, repoPath)
	if err != nil {
		return err
	}

	fmt.Println(successStyle.Render(fmt.Sprintf("Created PR: %s", pr.URL)))
	return nil
}

// generatePRDescription creates an auto-generated PR description
func generatePRDescription(results []RenderResult, config *RenderConfig) string {
	var sb strings.Builder

	sb.WriteString("## Summary\n\n")
	sb.WriteString("Rendered claim templates:\n\n")

	for _, r := range results {
		if r.Error == nil {
			sb.WriteString(fmt.Sprintf("- **%s** → `%s`\n", r.TemplateName, r.OutputPath))
		}
	}

	sb.WriteString("\n## Files Changed\n\n")
	for _, r := range results {
		if r.Error == nil && r.OutputPath != "" {
			sb.WriteString(fmt.Sprintf("- `%s`\n", r.OutputPath))
		}
	}

	sb.WriteString("\n---\n")
	sb.WriteString("*Generated by claims CLI*\n")

	return sb.String()
}
